# 第３部 Pythonによる記述統計

## 第1章　変量データ

In [1]:
import numpy as np
import scipy as sp

In [2]:
%precision 3

'%.3f'

https://github.com/numpy/numpy/issues/11048
https://github.com/numpy/numpy/pull/9201#issuecomment-332609336 ↑からリンクがあります。

で議論されていることに似ているようです。

numpy.float64 に対してstrやrepr関数を適用したときの結果は、Python組み込みのfloat型と同じように振る舞うべきである、という理念に基づいているようなので、手段はない(自分でフォーマットするしかない)かと思います。

In [51]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [52]:
# データの作成はnumpyで行い、データの操作はscipyで行う
sp.sum(fish_data)

40

In [53]:
len(fish_data)

10

In [54]:
# 平均値
N = len(fish_data)
sum_value = sp.sum(fish_data)
mu = sum_value / N
mu

4.0

In [8]:
# numpy.float64 に対してstrやrepr関数を適用したときの結果は、
# Python組み込みのfloat型と同じように振る舞うべきである、という理念に基づいているという証拠に以下は
# precisionのマジックコマンドが機能している
3 / 5

0.600

In [55]:
sigma_2_fish_data = sp.sum((fish_data - mu) ** 2) / N
sigma_2_fish_data

1.2

In [56]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [57]:
# 標本分散
# nで割る分散はddof=0で、n−1で割る不偏分散はddof=1
sp.var(fish_data, ddof = 0)

# var 平均とデータ数を自動で計算して、分散の公式に当てはめて計算してくれる

1.2

In [46]:
# 不偏分散　分散を過小に見積もってしまうというバイアスをなくした分散

sigma_2_fish_data = sp.sum((fish_data - mu) ** 2) / (N - 1)
sigma_2_fish_data

1.3333333333333333

In [68]:
sp.var(fish_data, ddof = 1)

1.3333333333333333

In [66]:
sigma = sp.sqrt(sigma_2_fish_data)
sigma

1.0954451150103321

In [67]:
sigma = sp.std(fish_data, ddof = 0)
sigma

1.0954451150103321

In [69]:
# 標準化
standard = (fish_data - mu) / sigma
standard

array([-1.826, -0.913, -0.913,  0.   ,  0.   ,  0.   ,  0.   ,  0.913,
        0.913,  1.826])

In [71]:
sp.mean(standard)

2.2204460492503132e-17

In [73]:
sp.std(standard, ddof = 0)

1.0